export const QUERY_KEYS = {
  CAMPAIGN_LIST: "campaignList",
  NONPROFIT_LIST: "nonprofitList",
  PROFILE_CAMPAIGNS: "profileCampaigns",
  PROFILE_DONATIONS: "profileDonations",
  PROFILE_COMMENTS: "profileComments",
  DASHBOARD_CAMPAIGNS: "dashboardCampaigns",
  DASHBOARD_NONPROFITS: "dashboardNonprofits",
  DASHBOARD_DONATIONS: "dashboardDonations",
  DASHBOARD_COMMENTS: "dashboardComments",
  DONATION: "donation",
  COMMENTS: "comments",
  ADMIN_CAMPAIGN_DETAIL: "adminCampaignDetail",
  ADMIN_NONPROFIT_DETAIL: "adminNonprofitDetail",
  CATEGORIES: "categories",
  LOCATIONS: "locations",
  CAMPAIGN_DETAIL: "campaignDetail",
  USER_CONVERSATION: "userConversation",
  ADMIN_CONVERSATIONS: "adminConversations",
  ADMIN_CHAT: "adminChat",
};
