export const QUERY_KEYS = {
  CAMPAIGN_LIST: "campaignList",
  NONPROFIT_LIST: "nonprofitList",
  PROFILE_CAMPAIGNS: "profileCampaigns",
  DASHBOARD_CAMPAIGNS: "dashboardCampaigns",
  DASHBOARD_NONPROFITS: "dashboardNonprofits",
  // ADMIN_RENTS: "adminRents",
  // ADMIN_RESERVATIONS: "adminReservations",
  // ADMIN_REVIEWS: "adminReviews",
  ADMIN_CAMPAIGN_DETAIL: "adminCampaignDetail",
  ADMIN_NONPROFIT_DETAIL: "adminNonprofitDetail",
  CATEGORIES: "categories",
  LOCATIONS: "locations",
  // RESERVATIONS: "reservations",
  // RECOMMENDATION_RENTS: "recommendationRents",
  // RENT_LIST: "rentList",
  CAMPAIGN_DETAIL: "campaignDetail",
  // USER_CONVERSATION: "userConversation",
  // ADMIN_CONVERSATIONS: "adminConversations",
  // ADMIN_CHAT: "adminChat",
};
